Exercise on Functions

In [7]:
#Task-1
def convert_units(conversion_type, value):
    """Converts units based on the selected conversion type."""

    if conversion_type == "1":  # meters to feet
        return value * 3.28084

    elif conversion_type == "2":  # feet to meters
        return value / 3.28084

    elif conversion_type == "3":  # kg to pounds
        return value * 2.20462

    elif conversion_type == "4":  # pounds to kg
        return value / 2.20462

    elif conversion_type == "5":  # liters to gallons
        return value * 0.264172

    elif conversion_type == "6":  # gallons to liters
        return value / 0.264172

    else:
        return None

def unit_converter():
    """Main function that asks the user for conversion type and value."""

    print("Unit Converter")
    print("Choose conversion type:")
    print("1. meters to feet")
    print("2. feet to meters")
    print("3. kilograms to pounds")
    print("4. pounds to kilograms")
    print("5. liters to gallons")
    print("6. gallons to liters")

    conversion_type = input("Enter option number: ")

    try:
        value = float(input("Enter value: "))

        result = convert_units(conversion_type, value)

        if result is None:
            print("Invalid conversion option")
        else:
            print("Converted value:", result)

    except ValueError:
        print("Invalid input. Please enter a number.")

unit_converter()

Unit Converter
Choose conversion type:
1. meters to feet
2. feet to meters
3. kilograms to pounds
4. pounds to kilograms
5. liters to gallons
6. gallons to liters
Enter option number: 1
Enter value: 10
Converted value: 32.8084


In [6]:
#Task-2
def find_sum(numbers):
    """Returns the sum of numbers in the list."""
    return sum(numbers)

def find_average(numbers):
    """Returns the average of numbers in the list."""
    return sum(numbers) / len(numbers)

def find_max(numbers):
    """Returns the maximum number in the list."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum number in the list."""
    return min(numbers)

def main():
    """Main function that asks the user to choose an operation and enter numbers."""

    print("Math Operations Program")
    print("1. Find Sum")
    print("2. Find Average")
    print("3. Find Maximum")
    print("4. Find Minimum")

    choice = input("Enter your choice: ")

    try:
        numbers_input = input("Enter numbers separated by spaces: ")

        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            print("Error: List cannot be empty")
            return

        if choice == "1":
            print("Sum:", find_sum(numbers))

        elif choice == "2":
            print("Average:", find_average(numbers))

        elif choice == "3":
            print("Maximum:", find_max(numbers))

        elif choice == "4":
            print("Minimum:", find_min(numbers))

        else:
            print("Invalid option")

    except ValueError:
        print("Error: Please enter valid numbers")

main()

Math Operations Program
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Enter your choice: 2
Enter numbers separated by spaces: 10 20 30 40
Average: 25.0


Exercise on List Manipulation

In [8]:
#1. Extract Every Other Element:
def extract_every_other(lst):
    """Return every other element from the list, starting with the first."""
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]

result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [4]:
#2. Slice a Sublist:
def get_sublist(lst, start, end):
    """
    This function returns a part of the list from start index to end index.
    """
    return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]
print(get_sublist(numbers, 2, 4))


[3, 4, 5]


In [5]:
#3. Reverse a List Using Slicing:
def reverse_list(lst):
    """
    This function reverses the list using slicing.
    """
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
print(reverse_list(numbers))

[5, 4, 3, 2, 1]


In [9]:
#4. Remove the First and Last Elements:
def remove_first_last(lst):
    """
    This function removes the first and last elements of a list.
    """
    return lst[1:-1]

numbers = [1, 2, 3, 4, 5]
print(remove_first_last(numbers))

[2, 3, 4]


In [10]:
#5. Get the First n Elements:
def get_first_n(lst, n):
    """
    This function returns the first n elements of a list.
    """
    return lst[:n]

numbers = [1, 2, 3, 4, 5]
print(get_first_n(numbers, 3))

[1, 2, 3]


In [11]:
#6. Extract Elements from the End:
def get_last_n(lst, n):
    """
    This function returns the last n elements of a list.
    """
    return lst[-n:]

numbers = [1, 2, 3, 4, 5]
print(get_last_n(numbers, 2))

[4, 5]


In [12]:
#7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    """
    This function returns every second element from the list
    starting from the second last element going backwards.
    """
    return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
print(reverse_skip(numbers))

[5, 3, 1]


Exercise on Nested List

In [13]:
# 1. Flatten a Nested List
def flatten(lst):
    """Flatten a nested list into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(item)
        else:
            flat_list.append(item)
    return flat_list

nested_list1 = [[10, 20], [30, 40], [50]]
print("Flattened:", flatten(nested_list1))


Flattened: [10, 20, 30, 40, 50]


In [14]:
# 2. Accessing Nested List Elements
def access_nested_element(lst, indices):
    """Access an element in a nested list using a list of indices."""
    elem = lst
    for idx in indices:
        elem = elem[idx]
    return elem

nested_list2 = [[11, 22, 33], [44, 55, 66], [77, 88, 99]]
print("Accessed element:", access_nested_element(nested_list2, [1, 2]))

Accessed element: 66


In [15]:
# 3. Sum of All Elements in a Nested List
def sum_nested(lst):
    """Return the sum of all elements in a nested list, regardless of depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list3 = [[1, 3], [5, [7, 9]], 2]
print("Sum:", sum_nested(nested_list3))

Sum: 27


In [16]:
# 4. Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """Remove all occurrences of an element from a nested list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

nested_list4 = [[3, 4], [4, 5], [6, 7]]
print("After removal:", remove_element(nested_list4, 4))

After removal: [[3], [5], [6, 7]]


In [17]:
# 5. Find the Maximum Element in a Nested List
def find_max(lst):
    """Find the maximum element in a nested list, regardless of depth."""
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

nested_list5 = [[2, 8], [10, [5, 12]], 7]
print("Maximum element:", find_max(nested_list5))

Maximum element: 12


In [18]:
# 6. Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """Count the occurrences of an element in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

nested_list6 = [[1, 5], [5, 7], [8, 5]]
print("Occurrences of 5:", count_occurrences(nested_list6, 5))

Occurrences of 5: 3


In [19]:
# 7. Flatten a List of Lists of Lists
def deep_flatten(lst):
    """Flatten a deeply nested list into a single list, regardless of depth."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

nested_list7 = [[[1, 2], [3, 4]], [[5, 6], [7, 9]]]
print("Deep flattened:", deep_flatten(nested_list7))

Deep flattened: [1, 2, 3, 4, 5, 6, 7, 9]


In [20]:
# 8. Nested List Average
def average_nested(lst):
    """Calculate the average of all elements in a nested list."""
    total_sum = sum_nested(lst)
    def count_elements(l):
        count = 0
        for item in l:
            if isinstance(item, list):
                count += count_elements(item)
            else:
                count += 1
        return count
    total_count = count_elements(lst)
    return total_sum / total_count if total_count != 0 else 0

nested_list8 = [[2, 4], [6, 8], [10, 12]]
print("Average:", average_nested(nested_list8))

Average: 7.0


Basic Vector and Matrix Operation with Numpy

Problem - 1: Array Creation:

In [21]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nArray filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
sample_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros like sample array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(sample_array)
print("\nOnes like sample array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list:\n", array_from_list)

Empty 2x2 array:
 [[3.07069013e-315 0.00000000e+000]
 [6.79585431e-310 5.77904633e-317]]

All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like sample array:
 [[0 0 0]
 [0 0 0]]

Ones like sample array:
 [[1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [22]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("Array from 10 to 49:\n", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix from 0 to 8:\n", arr2)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:\n", random_array)
print("Mean of array:", mean_value)

# 5. Create a 10x10 array with random values and find min & max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n10x10 random array:\n", random_10x10)
print("Min:", min_val, "Max:", max_val)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4)
print("\nZero array with 5th element as 1:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with border 1s and inside 0s:\n", border_array)

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 checkerboard pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.89048651 0.2897175  0.74607357 0.30519703 0.78397048 0.47127167
 0.19310643 0.83334222 0.6144134  0.11791134 0.9947605  0.71042137
 0.39651891 0.97262896 0.22741531 0.4151108  0.07376499 0.60699327
 0.47273661 0.56745697 0.12047992 0.21665665 0.44221242 0.58311604
 0.44757643 0.99136631 0.31847083 0.47764688 0.51385804 0.88602928]
Mean of array: 0.5226903541185277

10x10 random array:
 [[0.88837669 0.86148705 0.18287223 0.09874071 0.2990832  0.183673
  0.09444227 0.37019595 0.45568114 0.34694671]
 [0.74893901 0.04023022 0.92145553 0.67040073 0.2823329  0.46308271
  0.27687301 0.29086761 0.79604244 0.41956113]
 [0.58881274 0.89181953 0.08393712 0.9865755  0.13569663 0.21940113
  0.74054988 0.09673982 0.

Problem - 3: Array Operations:

In [23]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("x + y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3. Multiply the array with integers (let's choose 3)
mult_x = x * 3
print("\nx * 3:\n", mult_x)

# 4. Find the square of each element of the array
square_x = x**2
print("\nSquare of x:\n", square_x)

# 5. Dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v.w:", dot_vw)
print("Dot product x.v:\n", dot_xv)
print("Dot product x.y:\n", dot_xy)

# 6. Concatenate x and y along row (axis=0) and v and w along column (axis=0 first make 2D)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print("\nConcatenate x and y along rows:\n", concat_xy_row)
print("Concatenate v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v (will raise an error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError while concatenating x and v:", e)
    print("Explanation: x is 2D (2x2) and v is 1D (2,), so their dimensions do not match for concatenation.")

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

Square of x:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v:
 [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2D (2x2) and v is 1D (2,), so their dimensions do not match for concatenation.


Problem - 4: Matrix Operations:

In [24]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)

Matrix A:
 [[3 4]
 [7 8]]
Matrix B:
 [[5 3]
 [2 1]]


In [25]:
# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
I_check = np.dot(A, A_inv)

print("A * A^-1:\n", I_check)

# Check if it's close to identity
print("Is A * A^-1 close to identity?", np.allclose(I_check, np.eye(2)))

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^-1 close to identity? True


In [26]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("BA:\n", BA)

# Check if AB equals BA
print("Is AB equal to BA?", np.array_equal(AB, BA))

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False


In [27]:
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)

print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)

# Check if they are equal
print("Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True


In [28]:
# Represent system in matrix form AX = B
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_sys = np.array([-1, -3, 9])

# Solve using np.linalg.solve (direct method)
X = np.linalg.solve(A_sys, B_sys)
print("Solution using linalg.solve:\n", X)

Solution using linalg.solve:
 [ 2.  1. -2.]


In [29]:
# Compute inverse of A_sys
A_sys_inv = np.linalg.inv(A_sys)

# Solve X = A^-1 * B
X_inv = np.dot(A_sys_inv, B_sys)
print("Solution using inverse method:\n", X_inv)

Solution using inverse method:
 [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [36]:
import numpy as np
import time


Step 1: Element-wise Addition

In [31]:
def add_lists(list1, list2):
    start = time.time()
    result = [a + b for a, b in zip(list1, list2)]
    end = time.time()
    print("Python list addition time:", end - start, "seconds")
    return result

def add_arrays(arr1, arr2):
    start = time.time()
    result = arr1 + arr2
    end = time.time()
    print("NumPy array addition time:", end - start, "seconds")
    return result

Step 2: Element-wise Multiplication

In [32]:
def multiply_lists(list1, list2):
    start = time.time()
    result = [a * b for a, b in zip(list1, list2)]
    end = time.time()
    print("Python list multiplication time:", end - start, "seconds")
    return result

def multiply_arrays(arr1, arr2):
    start = time.time()
    result = arr1 * arr2
    end = time.time()
    print("NumPy array multiplication time:", end - start, "seconds")
    return result

Step 3: Dot Product

In [33]:
def dot_lists(list1, list2):
    start = time.time()
    result = sum(a * b for a, b in zip(list1, list2))
    end = time.time()
    print("Python list dot product time:", end - start, "seconds")
    return result

def dot_arrays(arr1, arr2):
    start = time.time()
    result = np.dot(arr1, arr2)
    end = time.time()
    print("NumPy array dot product time:", end - start, "seconds")
    return result

Step 4: Matrix Multiplication (1000x1000)

In [34]:
def matmul_lists(mat1, mat2):
    size = len(mat1)
    start = time.time()
    result = [[sum(mat1[i][k] * mat2[k][j] for k in range(size))
               for j in range(size)] for i in range(size)]
    end = time.time()
    print("Python list matrix multiplication time:", end - start, "seconds")
    return result

def matmul_arrays(mat1, mat2):
    start = time.time()
    result = np.dot(mat1, mat2)
    end = time.time()
    print("NumPy array matrix multiplication time:", end - start, "seconds")
    return result

Run the functions

In [37]:
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.arange(size)
arr2 = np.arange(size)

# Addition
add_lists(list1, list2)
add_arrays(arr1, arr2)

# Multiplication
multiply_lists(list1, list2)
multiply_arrays(arr1, arr2)

# Dot Product
dot_lists(list1, list2)
dot_arrays(arr1, arr2)

# Matrix Multiplication
matrix_size = 1000
mat1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
mat2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]
np_mat1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

matmul_lists(mat1, mat2)
matmul_arrays(np_mat1, np_mat2)

Python list addition time: 0.06315016746520996 seconds
NumPy array addition time: 0.002220630645751953 seconds
Python list multiplication time: 0.06134986877441406 seconds
NumPy array multiplication time: 0.002313852310180664 seconds
Python list dot product time: 0.09104466438293457 seconds
NumPy array dot product time: 0.0017349720001220703 seconds
Python list matrix multiplication time: 191.24373841285706 seconds
NumPy array matrix multiplication time: 1.8598597049713135 seconds


array([[   332833500000,    332833999500,    332834499000, ...,
           333331501500,    333332001000,    333332500500],
       [   832333500000,    832334999500,    832336499000, ...,
           833828501500,    833830001000,    833831500500],
       [  1331833500000,   1331835999500,   1331838499000, ...,
          1334325501500,   1334328001000,   1334330500500],
       ...,
       [498334333500000, 498335330999500, 498336328499000, ...,
        499328840501500, 499329838001000, 499330835500500],
       [498833833500000, 498834831999500, 498835830499000, ...,
        499829337501500, 499830336001000, 499831334500500],
       [499333333500000, 499334332999500, 499335332499000, ...,
        500329834501500, 500330834001000, 500331833500500]])